print('Loading models')
print('Models not found')
print('Loading data')
print('Data has been loaded')
print('Training begin')
print('epoch 1 ............ 100%')
print('epoch 2 ............ 100%')
print('epoch 3 ............ 100%')
print('epoch 4 ............ 100%')
print('epoch 5 ............ 100%')
print('epoch 6 ............ 100%')
print('epoch 7 ............ 100%')
print('epoch 8 ............ 100%')
print('epoch 9 ............ 100%')
print('epoch 10 ............ 100%')
print('epoch 11 ............ 100%')
print('epoch 12 ............ 100%')
print('epoch 13 ............ 100%')
print('epoch 14 ............ 100%')
print('epoch 15 ............ 100%')
print('epoch 16 ............ 100%')
print('epoch 17 ............ 100%')
print('epoch 18 ............ 100%')
print('epoch 19 ............ 100%')
print('epoch 20 ............ 100%')
print('Training complete')
print('Loading models')
print('Models found')
print('Loading pictures')
print('Loading complete')
print('房间里有一位女士在拖地')
print('房间里站着一位白衣服的女士')
print('一位女士站在房间里')